//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuOnWebFinal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnglishTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnglishTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MenuOnWebFinal.Resources.EnglishTexts", typeof(EnglishTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter here your ingredients with comma as separator.
        /// </summary>
        public static string _Layout1 {
            get {
                return ResourceManager.GetString("_Layout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string _Layout10 {
            get {
                return ResourceManager.GetString("_Layout10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string _Layout11 {
            get {
                return ResourceManager.GetString("_Layout11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is admin panel.
        /// </summary>
        public static string _Layout12 {
            get {
                return ResourceManager.GetString("_Layout12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign role.
        /// </summary>
        public static string _Layout13 {
            get {
                return ResourceManager.GetString("_Layout13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user.
        /// </summary>
        public static string _Layout14 {
            get {
                return ResourceManager.GetString("_Layout14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Log in.
        /// </summary>
        public static string _Layout15 {
            get {
                return ResourceManager.GetString("_Layout15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string _Layout16 {
            get {
                return ResourceManager.GetString("_Layout16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string _Layout17 {
            get {
                return ResourceManager.GetString("_Layout17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string _Layout18 {
            get {
                return ResourceManager.GetString("_Layout18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Sign up.
        /// </summary>
        public static string _Layout19 {
            get {
                return ResourceManager.GetString("_Layout19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string _Layout2 {
            get {
                return ResourceManager.GetString("_Layout2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login:.
        /// </summary>
        public static string _Layout20 {
            get {
                return ResourceManager.GetString("_Layout20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string _Layout21 {
            get {
                return ResourceManager.GetString("_Layout21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password(use special symbols):.
        /// </summary>
        public static string _Layout22 {
            get {
                return ResourceManager.GetString("_Layout22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password:.
        /// </summary>
        public static string _Layout23 {
            get {
                return ResourceManager.GetString("_Layout23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string _Layout24 {
            get {
                return ResourceManager.GetString("_Layout24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string _Layout25 {
            get {
                return ResourceManager.GetString("_Layout25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login:.
        /// </summary>
        public static string _Layout26 {
            get {
                return ResourceManager.GetString("_Layout26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string _Layout27 {
            get {
                return ResourceManager.GetString("_Layout27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string _Layout28 {
            get {
                return ResourceManager.GetString("_Layout28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add recipe.
        /// </summary>
        public static string _Layout29 {
            get {
                return ResourceManager.GetString("_Layout29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add recipe.
        /// </summary>
        public static string _Layout3 {
            get {
                return ResourceManager.GetString("_Layout3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe title:.
        /// </summary>
        public static string _Layout30 {
            get {
                return ResourceManager.GetString("_Layout30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe background image.
        /// </summary>
        public static string _Layout31 {
            get {
                return ResourceManager.GetString("_Layout31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        public static string _Layout32 {
            get {
                return ResourceManager.GetString("_Layout32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (use comma as separator).
        /// </summary>
        public static string _Layout33 {
            get {
                return ResourceManager.GetString("_Layout33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directions:.
        /// </summary>
        public static string _Layout34 {
            get {
                return ResourceManager.GetString("_Layout34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string _Layout35 {
            get {
                return ResourceManager.GetString("_Layout35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My recipes.
        /// </summary>
        public static string _Layout4 {
            get {
                return ResourceManager.GetString("_Layout4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My favorite.
        /// </summary>
        public static string _Layout5 {
            get {
                return ResourceManager.GetString("_Layout5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string _Layout6 {
            get {
                return ResourceManager.GetString("_Layout6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string _Layout7 {
            get {
                return ResourceManager.GetString("_Layout7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter here your ingredients with comma as separator.
        /// </summary>
        public static string _Layout8 {
            get {
                return ResourceManager.GetString("_Layout8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string _Layout9 {
            get {
                return ResourceManager.GetString("_Layout9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string _LoginPartial1 {
            get {
                return ResourceManager.GetString("_LoginPartial1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string _LoginPartial2 {
            get {
                return ResourceManager.GetString("_LoginPartial2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string _LoginPartial3 {
            get {
                return ResourceManager.GetString("_LoginPartial3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string _LoginPartial4 {
            get {
                return ResourceManager.GetString("_LoginPartial4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About1 {
            get {
                return ResourceManager.GetString("About1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this area to provide additional information..
        /// </summary>
        public static string About2 {
            get {
                return ResourceManager.GetString("About2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string AddPhoneNumber1 {
            get {
                return ResourceManager.GetString("AddPhoneNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a phone number.
        /// </summary>
        public static string AddPhoneNumber2 {
            get {
                return ResourceManager.GetString("AddPhoneNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssignRole.
        /// </summary>
        public static string AssignRole1 {
            get {
                return ResourceManager.GetString("AssignRole1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign role.
        /// </summary>
        public static string AssignRole2 {
            get {
                return ResourceManager.GetString("AssignRole2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string AssignRole3 {
            get {
                return ResourceManager.GetString("AssignRole3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Role.
        /// </summary>
        public static string AssignRole4 {
            get {
                return ResourceManager.GetString("AssignRole4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string AssignRole5 {
            get {
                return ResourceManager.GetString("AssignRole5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword1 {
            get {
                return ResourceManager.GetString("ChangePassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Form.
        /// </summary>
        public static string ChangePassword2 {
            get {
                return ResourceManager.GetString("ChangePassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email. Please.
        /// </summary>
        public static string ConfirmEmail1 {
            get {
                return ResourceManager.GetString("ConfirmEmail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to Log in.
        /// </summary>
        public static string ConfirmEmail2 {
            get {
                return ResourceManager.GetString("ConfirmEmail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact1 {
            get {
                return ResourceManager.GetString("Contact1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support:.
        /// </summary>
        public static string Contact2 {
            get {
                return ResourceManager.GetString("Contact2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing:.
        /// </summary>
        public static string Contact3 {
            get {
                return ResourceManager.GetString("Contact3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Recipe.
        /// </summary>
        public static string Create1 {
            get {
                return ResourceManager.GetString("Create1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Create2 {
            get {
                return ResourceManager.GetString("Create2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directions:.
        /// </summary>
        public static string Create3 {
            get {
                return ResourceManager.GetString("Create3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        public static string Create4 {
            get {
                return ResourceManager.GetString("Create4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (use comma as separator).
        /// </summary>
        public static string Create5 {
            get {
                return ResourceManager.GetString("Create5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Create6 {
            get {
                return ResourceManager.GetString("Create6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Create7 {
            get {
                return ResourceManager.GetString("Create7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteUser.
        /// </summary>
        public static string DeleteUser1 {
            get {
                return ResourceManager.GetString("DeleteUser1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user.
        /// </summary>
        public static string DeleteUser2 {
            get {
                return ResourceManager.GetString("DeleteUser2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Role.
        /// </summary>
        public static string DeleteUser3 {
            get {
                return ResourceManager.GetString("DeleteUser3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string DeleteUser4 {
            get {
                return ResourceManager.GetString("DeleteUser4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details1 {
            get {
                return ResourceManager.GetString("Details1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete it.
        /// </summary>
        public static string Details10 {
            get {
                return ResourceManager.GetString("Details10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstly log in or register.
        /// </summary>
        public static string Details11 {
            get {
                return ResourceManager.GetString("Details11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        public static string Details2 {
            get {
                return ResourceManager.GetString("Details2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directions.
        /// </summary>
        public static string Details3 {
            get {
                return ResourceManager.GetString("Details3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments after directions.
        /// </summary>
        public static string Details4 {
            get {
                return ResourceManager.GetString("Details4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add comment:.
        /// </summary>
        public static string Details5 {
            get {
                return ResourceManager.GetString("Details5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Info.
        /// </summary>
        public static string Details6 {
            get {
                return ResourceManager.GetString("Details6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from favorite.
        /// </summary>
        public static string Details7 {
            get {
                return ResourceManager.GetString("Details7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to favorite.
        /// </summary>
        public static string Details8 {
            get {
                return ResourceManager.GetString("Details8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit recipe.
        /// </summary>
        public static string Details9 {
            get {
                return ResourceManager.GetString("Details9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dislike :(.
        /// </summary>
        public static string Dislike {
            get {
                return ResourceManager.GetString("Dislike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Recipe.
        /// </summary>
        public static string Edit1 {
            get {
                return ResourceManager.GetString("Edit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Edit2 {
            get {
                return ResourceManager.GetString("Edit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directions:.
        /// </summary>
        public static string Edit3 {
            get {
                return ResourceManager.GetString("Edit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        public static string Edit4 {
            get {
                return ResourceManager.GetString("Edit4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (use comma as separator).
        /// </summary>
        public static string Edit5 {
            get {
                return ResourceManager.GetString("Edit5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Edit6 {
            get {
                return ResourceManager.GetString("Edit6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Eedit1 {
            get {
                return ResourceManager.GetString("Eedit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit account.
        /// </summary>
        public static string Eedit2 {
            get {
                return ResourceManager.GetString("Eedit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login:.
        /// </summary>
        public static string Eedit3 {
            get {
                return ResourceManager.GetString("Eedit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string Eedit4 {
            get {
                return ResourceManager.GetString("Eedit4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number:.
        /// </summary>
        public static string Eedit5 {
            get {
                return ResourceManager.GetString("Eedit5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Eedit6 {
            get {
                return ResourceManager.GetString("Eedit6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Eedit7 {
            get {
                return ResourceManager.GetString("Eedit7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error1 {
            get {
                return ResourceManager.GetString("Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error..
        /// </summary>
        public static string Error2 {
            get {
                return ResourceManager.GetString("Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string Error3 {
            get {
                return ResourceManager.GetString("Error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string ExternalLoginConfirmation1 {
            get {
                return ResourceManager.GetString("ExternalLoginConfirmation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate your.
        /// </summary>
        public static string ExternalLoginConfirmation2 {
            get {
                return ResourceManager.GetString("ExternalLoginConfirmation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account..
        /// </summary>
        public static string ExternalLoginConfirmation3 {
            get {
                return ResourceManager.GetString("ExternalLoginConfirmation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association Form.
        /// </summary>
        public static string ExternalLoginConfirmation4 {
            get {
                return ResourceManager.GetString("ExternalLoginConfirmation4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully authenticated with.
        /// </summary>
        public static string ExternalLoginConfirmation5 {
            get {
                return ResourceManager.GetString("ExternalLoginConfirmation5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a user name for this site below and click the Register button to finish
        ///        logging in..
        /// </summary>
        public static string ExternalLoginConfirmation6 {
            get {
                return ResourceManager.GetString("ExternalLoginConfirmation6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string ExternalLoginConfirmation7 {
            get {
                return ResourceManager.GetString("ExternalLoginConfirmation7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failure.
        /// </summary>
        public static string ExternalLoginFailure1 {
            get {
                return ResourceManager.GetString("ExternalLoginFailure1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful login with service..
        /// </summary>
        public static string ExternalLoginFailure2 {
            get {
                return ResourceManager.GetString("ExternalLoginFailure2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no external authentication services configured. See.
        /// </summary>
        public static string ExternalLoginsListPartial1 {
            get {
                return ResourceManager.GetString("ExternalLoginsListPartial1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this article.
        /// </summary>
        public static string ExternalLoginsListPartial2 {
            get {
                return ResourceManager.GetString("ExternalLoginsListPartial2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for details on setting up this ASP.NET application to support logging in via external services..
        /// </summary>
        public static string ExternalLoginsListPartial3 {
            get {
                return ResourceManager.GetString("ExternalLoginsListPartial3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using your.
        /// </summary>
        public static string ExternalLoginsListPartial4 {
            get {
                return ResourceManager.GetString("ExternalLoginsListPartial4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account.
        /// </summary>
        public static string ExternalLoginsListPartial5 {
            get {
                return ResourceManager.GetString("ExternalLoginsListPartial5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service to log in..
        /// </summary>
        public static string ExternalLoginsListPartial6 {
            get {
                return ResourceManager.GetString("ExternalLoginsListPartial6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotPassword1 {
            get {
                return ResourceManager.GetString("ForgotPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email..
        /// </summary>
        public static string ForgotPassword2 {
            get {
                return ResourceManager.GetString("ForgotPassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Confirmation.
        /// </summary>
        public static string ForgotPasswordConfirmation1 {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        public static string ForgotPasswordConfirmation2 {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetFavourites.
        /// </summary>
        public static string GetFavourites1 {
            get {
                return ResourceManager.GetString("GetFavourites1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more.
        /// </summary>
        public static string GetFavourites2 {
            get {
                return ResourceManager.GetString("GetFavourites2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Iindex1 {
            get {
                return ResourceManager.GetString("Iindex1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account settings.
        /// </summary>
        public static string Iindex2 {
            get {
                return ResourceManager.GetString("Iindex2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Iindex3 {
            get {
                return ResourceManager.GetString("Iindex3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Logins:.
        /// </summary>
        public static string Iindex4 {
            get {
                return ResourceManager.GetString("Iindex4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Factor Authentication:.
        /// </summary>
        public static string Iindex5 {
            get {
                return ResourceManager.GetString("Iindex5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no two-factor authentication providers configured. See.
        /// </summary>
        public static string Iindex6 {
            get {
                return ResourceManager.GetString("Iindex6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this article.
        /// </summary>
        public static string Iindex7 {
            get {
                return ResourceManager.GetString("Iindex7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for details on setting up this ASP.NET application to support two-factor authentication..
        /// </summary>
        public static string Iindex8 {
            get {
                return ResourceManager.GetString("Iindex8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string Index1 {
            get {
                return ResourceManager.GetString("Index1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more.
        /// </summary>
        public static string Index2 {
            get {
                return ResourceManager.GetString("Index2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I like it :).
        /// </summary>
        public static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked Out.
        /// </summary>
        public static string Lockout1 {
            get {
                return ResourceManager.GetString("Lockout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked out..
        /// </summary>
        public static string Lockout2 {
            get {
                return ResourceManager.GetString("Lockout2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again later..
        /// </summary>
        public static string Lockout3 {
            get {
                return ResourceManager.GetString("Lockout3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login1 {
            get {
                return ResourceManager.GetString("Login1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string Login2 {
            get {
                return ResourceManager.GetString("Login2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Login3 {
            get {
                return ResourceManager.GetString("Login3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Login4 {
            get {
                return ResourceManager.GetString("Login4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your external logins.
        /// </summary>
        public static string ManageLogins1 {
            get {
                return ResourceManager.GetString("ManageLogins1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no external authentication services configured. See.
        /// </summary>
        public static string ManageLogins2 {
            get {
                return ResourceManager.GetString("ManageLogins2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this article.
        /// </summary>
        public static string ManageLogins3 {
            get {
                return ResourceManager.GetString("ManageLogins3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for details on setting up this ASP.NET application to support logging in via external services..
        /// </summary>
        public static string ManageLogins4 {
            get {
                return ResourceManager.GetString("ManageLogins4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Logins.
        /// </summary>
        public static string ManageLogins5 {
            get {
                return ResourceManager.GetString("ManageLogins5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this.
        /// </summary>
        public static string ManageLogins6 {
            get {
                return ResourceManager.GetString("ManageLogins6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login from your account.
        /// </summary>
        public static string ManageLogins7 {
            get {
                return ResourceManager.GetString("ManageLogins7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using your.
        /// </summary>
        public static string ManageLogins8 {
            get {
                return ResourceManager.GetString("ManageLogins8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account.
        /// </summary>
        public static string ManageLogins9 {
            get {
                return ResourceManager.GetString("ManageLogins9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyRecipes.
        /// </summary>
        public static string MyRecipes1 {
            get {
                return ResourceManager.GetString("MyRecipes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more.
        /// </summary>
        public static string MyRecipes2 {
            get {
                return ResourceManager.GetString("MyRecipes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register1 {
            get {
                return ResourceManager.GetString("Register1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login:.
        /// </summary>
        public static string Register2 {
            get {
                return ResourceManager.GetString("Register2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string Register3 {
            get {
                return ResourceManager.GetString("Register3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Register4 {
            get {
                return ResourceManager.GetString("Register4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password:.
        /// </summary>
        public static string Register5 {
            get {
                return ResourceManager.GetString("Register5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number:.
        /// </summary>
        public static string Register6 {
            get {
                return ResourceManager.GetString("Register6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Register7 {
            get {
                return ResourceManager.GetString("Register7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Register8 {
            get {
                return ResourceManager.GetString("Register8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPassword1 {
            get {
                return ResourceManager.GetString("ResetPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password..
        /// </summary>
        public static string ResetPassword2 {
            get {
                return ResourceManager.GetString("ResetPassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password confirmation.
        /// </summary>
        public static string ResetPasswordConfirmation1 {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset. Please.
        /// </summary>
        public static string ResetPasswordConfirmation2 {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here to log in.
        /// </summary>
        public static string ResetPasswordConfirmation3 {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string SendCode1 {
            get {
                return ResourceManager.GetString("SendCode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send verification code.
        /// </summary>
        public static string SendCode2 {
            get {
                return ResourceManager.GetString("SendCode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Two-Factor Authentication Provider:.
        /// </summary>
        public static string SendCode3 {
            get {
                return ResourceManager.GetString("SendCode3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Password.
        /// </summary>
        public static string SetPassword1 {
            get {
                return ResourceManager.GetString("SetPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have a local username/password for this site. Add a local
        ///    account so you can log in without an external login..
        /// </summary>
        public static string SetPassword2 {
            get {
                return ResourceManager.GetString("SetPassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Local Login.
        /// </summary>
        public static string SetPassword3 {
            get {
                return ResourceManager.GetString("SetPassword3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string VerifyCode1 {
            get {
                return ResourceManager.GetString("VerifyCode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter verification code.
        /// </summary>
        public static string VerifyCode2 {
            get {
                return ResourceManager.GetString("VerifyCode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Phone Number.
        /// </summary>
        public static string VerifyPhoneNumber1 {
            get {
                return ResourceManager.GetString("VerifyPhoneNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter verification code.
        /// </summary>
        public static string VerifyPhoneNumber2 {
            get {
                return ResourceManager.GetString("VerifyPhoneNumber2", resourceCulture);
            }
        }
    }
}
